import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeCookie } from "./lib/cookie";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = ThemeCookie.get();
  return (
    <html lang="en" className={theme}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
